### ISSUE TITLE
Not all Icons viewed well

### ISSUE THREAD

**Issue by macik** [Alex300/cotonti-cpanel#1]
using FontAwesome 4.2 and Bootstrap 3.3.1
in latest Chrome.

See screen:
![image](https://cloud.githubusercontent.com/assets/1009926/5561126/9cf850da-8dd0-11e4-9dc3-34e63830e37b.png)

**Comment by Alex300** [comment]
I have no this issue on all my sites

**Comment by macik** [comment]
Ok. I'll check it more carefull. Then post it here.

**Comment by Alex300** [comment]
You need to clear your browser cache.
Perhaps it contains an older version of Font Awesome
